% Set NETSIM_AUTO environment variable to avoid keyboard interrupt at the end of each simulation
setenv('NETSIM_AUTO','1');
% Set the path of 64 bit NetSim Binaries to be used for simulation.
prompt = "Enter NetSim Binaries Path: "
NETSIM_PATH = input(prompt,'s')
%set License Path or IP address
prompt = "Enter LICENSE ARG Path: "
LICENSE_ARG = input(prompt,'s')
%Folder to run batch automation
prompt = "Enter Folder loaction of Configuration files: "
from_folder = input(prompt,'s')
filelist = dir(fullfile(from_folder, '**\*.netsim'));
% Iterate through all files
for i = 1:length(filelist)
    cmd="start ""NetSim_Batch_Automation"" /wait /d "...
    +""""... 
    +NETSIM_PATH...
    + """ "... 
    + "NetSimcore.exe -apppath """...
    +NETSIM_PATH...
    + """ -iopath """... 
    +filelist(i,1).folder... 
    +""" -license "...
    +LICENSE_ARG;
    system(cmd)
end